services:
  - type: web
    name: skillgenome-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: BACKEND_CORS_ORIGIN
        value: "*"
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0
